### ISSUE TITLE
Django landing page server error

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#266]
If you refresh the landing page a bunch and look at the `python manage.py runserver` output, you'll eventually see this error:

```
[30/May/2020 16:34:51] "GET /api/terms HTTP/1.1" 200 2521
[30/May/2020 16:34:51] "GET / HTTP/1.1" 200 893
[30/May/2020 16:34:51] "GET / HTTP/1.1" 200 893
[30/May/2020 16:34:51] "GET /static/main.js HTTP/1.1" 200 745472
Traceback (most recent call last):
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\old Python37-32\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
[30/May/2020 16:34:51] "GET /static/main.js HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57253)
Traceback (most recent call last):
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\old Python37-32\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Users\Gannon\Documents\workspace\web dev\Automatic-Aggie-Scheduler\env\lib\site-packages\django\core\servers\basehttp.py", line 116, in handle_error
    super().handle_error()
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\old Python37-32\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\old Python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\old Python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Gannon\Documents\workspace\web dev\Automatic-Aggie-Scheduler\env\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Users\Gannon\Documents\workspace\web dev\Automatic-Aggie-Scheduler\env\lib\site-packages\django\core\servers\basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "C:\old Python37-32\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Users\Gannon\Documents\workspace\web dev\Automatic-Aggie-Scheduler\env\lib\site-packages\django\core\servers\basehttp.py", line 111, in close 
    super().close()
  File "C:\old Python37-32\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

I have no idea why this happens, but we should probably investigate into it. Might be related to my setup, so I'd like it if y'all could try it out and see if it happens for y'all as well.

**Comment by firejake308** [comment]
Seems related to [this error](https://stackoverflow.com/questions/8814802/python-errno-10054-an-existing-connection-was-forcibly-closed-by-the-remote-h). As far as I can tell, it's just because you're refreshing the page too fast, and not a problem with our setup. Will mark as closed for now
