### ISSUE TITLE
Handle unavailable schedules in /sessions/get_saved_schedules

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#567]
We currently get the below error occasionally. I am very confident that this is because of the old data that we were displaying before 4/27 when the new courses were released (which they had saved, but the courses no longer exist), so I'm not *too* worried about this, but we might as well handle the case since it should be a pretty simple fix. 

```
"Exception raised handling request to GET /sessions/get_saved_schedules?term=202131.
Request body:
b''
Stack trace information:
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/srv/user_sessions/views.py", line 121, in get_saved_schedules
    serialized = _serialize_schedules(section_tuples)
  File "/srv/scheduler/views.py", line 69, in _serialize_schedules
    return [sections_for_schedule(schedule) for schedule in schedules]
  File "/srv/scheduler/views.py", line 69, in <listcomp>
    return [sections_for_schedule(schedule) for schedule in schedules]
  File "/srv/scheduler/views.py", line 67, in sections_for_schedule
    return SectionSerializer(sections, many=True).data
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super(ListSerializer, self).data
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/rest_framework/serializers.py", line 686, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/srv/scheduler/views.py", line 65, in <genexpr>
    sections = (sections_dict[section] for section in schedule)
KeyError: 598365
" 
```

**Comment by gannonprudhomme** [comment]
We also need to handle this situation on the frontend - the schedule preview is unusable as it keeps loading forever when it returns a 400 error.
